language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
    allow_failures:
        - php: 7.0

sudo: true

install: travis_retry composer install --no-interaction --prefer-source

before_script:
  - php artisan serve --quiet 2>&1>/dev/null &
  - phantomjs --webdriver=4444 2>&1>/dev/null &
  - sleep 5

script:
#  - vendor/bin/codecept run --skip acceptance
  - vendor/bin/codecept build
  - vendor/bin/codecept run

after_failure:
  - cat storage/logs/*
